FROM python:3.11-slim

RUN apt-get update

WORKDIR /app

COPY ./app .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token='token'", "--password='password'"]