FROM python:3.12-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      curl \
      git \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./app .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# 7. Expongo el puerto y arranco Uvicorn
EXPOSE 80

CMD [ "uvicorn" , "main:app", "--reload","--host", "0.0.0.0", "--port", "80"]

